version: '3.1'
services:

  nginx:
    image: nginx:nginx:1.15.8
#    image: nginx:1.15.8-alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./etc/nginx:/etc/nginx
      - ./logs/nginx:/var/log/nginx
      - ./htmls:/var/www/html:rw
    links:
      - php

  mysql:
    image: mariadb:10.3.12
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./etc/mariadb:/etc/mysql
      - ./db.data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: xuDiablodb
      MYSQL_USER: xuDiablo
      MYSQL_PASSWORD: xuP7t7YndGMdui
      MYSQL_ROOT_PASSWORD: 2P2hCSrP2mt@xuui

  php:
#    image: php:7.3-fpm
    image: wordpress:php7.3-fpm
#    image: wordpress:php7.3-fpm-alpine
    restart: always
#    ports:
#      - '9000:9000'
    volumes:
      - ./etc/php:/usr/local/etc
      - ./htmls:/var/www/html:rw
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: xuDiablodb
      WORDPRESS_DB_USER: xuDiablo
      WORDPRESS_DB_PASSWORD: xuP7t7YndGMdui
      WORDPRESS_TABLE_PREFIX: diablo_
    links:
      - mysql
